### Register user
POST http://localhost:8080/registrieren
Content-Type:application/json

{
 "username": "adem",
 "password": "12345",
 "password2": "12345"
}

### Login user
POST http://localhost:8080/login
Content-Type:application/json

{
"username": "asdew",
"password": "12345"
}

### Logout user
POST http://localhost:8080/logout
Content-Type:application/json

### Get user information
GET http://localhost:8080/user
Content-Type:application/json

### Get current rank for user
GET http://localhost:8080/rank

###
GET http://localhost:8080/artikel
Content-Type:application/json

###
POST http://localhost:8080/kommentar
Content-Type:application/json

{
"blogArtikelId": "1",
"inhalt": "schoener Artikel"
}

### Get all Users
GET http://localhost:8080/users


### Post
POST http://localhost:8080/users/1
Content-Type: application/json

